version: '3.9'

services:
  pg:
    image: postgres:alpine
    container_name: prescott-develop-pg
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - local

volumes:
  pg_data:

networks:
  local:
    name: prescott-local
    external: false
